/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   paper-chip-autocomplete.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.

import {PaperChipAutocomplete} from './PaperChipAutocomplete.js';

export {PaperChipAutocomplete};
